GestorDeContratos.Web/Controllers/ClienteController.cs
using Factoring.Utiles;
using GestorDeContratos.BLL.ServiceImplementation;
using GestorDeContratos.ServiceLayer.Service;
using GestorDeContratos.ServiceLayer.ViewsDTOs;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorDeContratos.ServiceLayer;

namespace GestorDeContratos.Web.Controllers
{
    public class ClienteController : Controller
    {
        readonly IGestorDeContratosSvcImpl gestorDeContratos;
        
        public ClienteController()
        {
            gestorDeContratos = new GestorDeContratosSvcImpl();
        }

        //
        // GET: /Cliente/Rut/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id = 0)
        {
            ViewData["RutCliente"] = id;
            PopulateCategories();
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Cliente_Buscar([DataSourceRequest] DataSourceRequest request, string buscar)
        {
            IEnumerable<ClienteDTO> lista = new List<ClienteDTO>();
            lista = gestorDeContratos.obtenerClientes(buscar);

            return Json(lista.ToDataSourceResult(request));
        }

        public ActionResult Cliente_Read(int rut)
        {
            bool procesoCorrecto = false;
            string mensajeRetorno = "";

            IEnumerable<ClienteDTO> lista = new List<ClienteDTO>();
            ClienteDTO cliente = new ClienteDTO();

            try
            {
                lista = gestorDeContratos.obtenerCliente(rut);
                if (lista.Count() > 0)
                {
                    procesoCorrecto = true;
                    mensajeRetorno = "Datos cargados correctamente";
                    cliente.rut = rut;
                    cliente.dv = lista.FirstOrDefault().dv.ToString();
                    cliente.razonSocial = lista.FirstOrDefault().razonSocial.ToString();
                    cliente.nombreCalle = lista.FirstOrDefault().nombreCalle.ToString();
                    cliente.numeroCalle = lista.FirstOrDefault().numeroCalle.ToString();
                    cliente.letraCalle = lista.FirstOrDefault().letraCalle.ToString();
                    cliente.comuna = lista.FirstOrDefault().comuna.ToString();
                    cliente.ciudad = lista.FirstOrDefault().ciudad.ToString();
                    cliente.region = lista.FirstOrDefault().region.ToString();
                    cliente.pais = lista.FirstOrDefault().pais.ToString();
                    cliente.codigoPostal = lista.FirstOrDefault().codigoPostal.ToString();
                    cliente.autorizaCartaPoder = lista.FirstOrDefault().autorizaCartaPoder.ToString();
                    cliente.email1 = lista.FirstOrDefault().email1.ToString();
                    cliente.email2 = lista.FirstOrDefault().email2.ToString();
                    //cliente.fechaFirmaContrato = (DateTime)lista.FirstOrDefault().fechaFirmaContrato2;
                    cliente.fechaFirmaContratoStr = lista.FirstOrDefault().fechaFirmaContratoStr;
                    cliente.repertorio = lista.FirstOrDefault().repertorio;
                    cliente.idNotaria = lista.FirstOrDefault().idNotaria;
                    cliente.autorizaFirmarNombre = lista.FirstOrDefault().autorizaFirmarNombre;
                    cliente.autorizaFirmarRut = lista.FirstOrDefault().autorizaFirmarRut;
                    cliente.esPersonaNatural = lista.FirstOrDefault().esPersonaNatural;
                    cliente.nacionalidadPersonaNatural = lista.FirstOrDefault().nacionalidadPersonaNatural;
                    cliente.profesionPersonaNatural = lista.FirstOrDefault().profesionPersonaNatural;
                    cliente.telefonoPersonaNatural = lista.FirstOrDefault().telefonoPersonaNatural;
                    cliente.idEstadoCivilPersonaNatural = lista.FirstOrDefault().idEstadoCivilPersonaNatural;
                    cliente.rutConyuge = lista.FirstOrDefault().rutConyuge;
                    cliente.dvConyuge = lista.FirstOrDefault().dvConyuge;
                    cliente.nombreConyuge = lista.FirstOrDefault().nombreConyuge;
                    cliente.nacionalidadConyuge = lista.FirstOrDefault().nacionalidadConyuge;
                    cliente.idSucursal = lista.FirstOrDefault().idSucursal;
                }
            }
            catch (Exception ex)
            {
                mensajeRetorno = ex.Message;
            }

            return new JsonResult
            {
                ContentType = "text/html",
                Data = new
                {
                    success = procesoCorrecto,
                    mensajeRetorno,
                    cliente.rut,
                    cliente.dv,
                    cliente.razonSocial,
                    cliente.nombreCalle,
                    cliente.numeroCalle,
                    cliente.letraCalle,
                    cliente.comuna,
                    cliente.ciudad,
                    cliente.region,
                    cliente.pais,
                    cliente.codigoPostal,
                    cliente.autorizaCartaPoder,
                    cliente.email1,
                    cliente.email2,
                    //cliente.fechaFirmaContrato,
                    cliente.fechaFirmaContratoStr,
                    cliente.repertorio,
                    cliente.idNotaria,
                    cliente.autorizaFirmarNombre,
                    cliente.autorizaFirmarRut,
                    cliente.esPersonaNatural,
                    cliente.nacionalidadPersonaNatural,
                    cliente.profesionPersonaNatural,
                    cliente.telefonoPersonaNatural,
                    cliente.idEstadoCivilPersonaNatural,
                    cliente.rutConyuge,
                    cliente.dvConyuge,
                    cliente.nombreConyuge,
                    cliente.nacionalidadConyuge,
                    cliente.idSucursal,
                }
            };
        }

        public ActionResult EstadosCiviles_Read()
        {
            IEnumerable<EstadoCivilDTO> lista = new List<EstadoCivilDTO>();
            lista = gestorDeContratos.obtenerEstadosCiviles();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Cliente_Update(int rut, char dv, string rutPalabra, string razonSocial, string nombreCalle, string numeroCalle, string numeroCallePalabra, string letraCalle, 
            string comuna, string ciudad, string autorizaCartaPoder, string email1, string email2, DateTime? fechaFirmaContrato, string repertorio, int idNotaria, string autorizaFirmarNombre,
            string autorizaFirmarRut, bool esPersonaNatural, string nacionalidadPersonaNatural, string profesionPersonaNatural, string telefonoPersonaNatural, int? rutConyuge, char? dvConyuge, 
            string nombreConyuge, string nacionalidadConyuge, int idSucursal, int? idEstadoCivilPersonaNatural)
        {
            bool procesoCorrecto = false;
            string mensajeRetorno = "Datos cargados correctamente!";

            try
            {
                //Conversion de números en palabras
                //FuncionesUtiles funcionesUtiles = new FuncionesUtiles();
                //rutPalabra = funcionesUtiles.convertirRutEnPalabras(rut, dv.ToString());
                //numeroCallePalabra = funcionesUtiles.convertirNumeroEnPalabras(numeroCalle.ToString());

                gestorDeContratos.actualizarCliente(rut, dv, rutPalabra, razonSocial, nombreCalle, numeroCalle, numeroCallePalabra, letraCalle, comuna, ciudad, autorizaCartaPoder, email1,
                    email2, fechaFirmaContrato, repertorio, idNotaria, autorizaFirmarNombre, autorizaFirmarRut, esPersonaNatural, nacionalidadPersonaNatural, profesionPersonaNatural, telefonoPersonaNatural, idEstadoCivilPersonaNatural,
                    rutConyuge, dvConyuge, nombreConyuge, nacionalidadConyuge, idSucursal);

                procesoCorrecto = true;
            }
            catch (Exception ex)
            {
                mensajeRetorno = ex.Message.ToString();
            }

            return new JsonResult
            {
                ContentType = "text/html",
                Data = new { success = procesoCorrecto, mensajeRetorno }
            };
        }

        private void PopulateCategories()
        {
            IEnumerable<EstadoCivilDTO> lista = new List<EstadoCivilDTO>();
            lista = gestorDeContratos.obtenerEstadosCiviles();

            ViewData["categories"] = lista;
            ViewData["defaultCategory"] = lista.First();
        }

        public ActionResult Operaciones_Read(int tipoOperacion, int rutCliente)
        {
            IEnumerable<OperacionListDTO> lista = new List<OperacionListDTO>();
            lista = gestorDeContratos.obtenerOperaciones(tipoOperacion, rutCliente);
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult OperacionesCursadas_Read([DataSourceRequest] DataSourceRequest request, int rutCliente)
        {
            IEnumerable<OperacionCursadaDTO> lista = new List<OperacionCursadaDTO>();
            lista = gestorDeContratos.obtenerOperacionesCursadas(rutCliente);
            return Json(lista.ToDataSourceResult(request));
        }
    }
}

GestorDeContratos.Web/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Busqueda de Clientes";
}
<br />

<script>
    kendo.culture("es-CL");
</script>

<script>
    function onClickBuscar() {
        $("#gridClientes").data("kendoGrid").dataSource.read();
    }

    function dataGridClientes() {
        return {
            buscar: $("#buscarTxt").val(),
        };
    }

    function datePicker(element) {
        element.kendoDatePicker({
            format: "dd/MM/yyyy"
        });
    }
</script>


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><b>BUSCAR CLIENTE</b></div>
        <div class="panel-body">
            <form id="buscarForm" class="form-horizontal" action="javascript:onClickBuscar();">
                <div class="form-group">
                    <label class="control-label col-sm-2" for="rut">Rut / Nombre:</label>
                    <div class="col-sm-10">
                        @(Html.Kendo().TextBox()
                            .Name("buscarTxt")
                            .HtmlAttributes(new { title = "Ingrese un rut (sin guion, ni dígito verificador), o nombre del cliente.", style = "width:120px" })
                        )
                    </div>
                </div>
                <div class="form-group"> 
                    <div class="col-sm-offset-2 col-sm-12">
                        @(Html.Kendo().Button()
                            .Name("buscarButton")
                            .HtmlAttributes( new {type = "button", @class = "k-primary" } )
                            .Content("Buscar")
                            .Events(ev => ev.Click("onClickBuscar"))
                        ) 
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><b>RESULTADOS</b></div>
        <div class="panel-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-18 col-md-12">
                        @(Html.Kendo().Grid<GestorDeContratos.ServiceLayer.ViewsDTOs.ClienteDTO>()
                            .Name("gridClientes")
                            .Columns(columns =>
                            {
                                columns.Bound(p => p.rut)
                                    .ClientTemplate(@Html.ActionLink("#= rut #-#= dv #", "Details", "Cliente", new { id = "#: rut #" }, null).ToString())
                                    .Title("RUT").Width(100)
                                    .Filterable(ftb => ftb.Search(true))
                                ;
                                columns.Bound(p => p.razonSocial).Title("NOMBRE/RAZÓN SOCIAL").Width(300);
                                columns.Bound(p => p.nombreCalle).Title("DIRECCIÓN").Width(300);
                                columns.Bound(p => p.comuna).Title("COMUNA");
                                columns.Bound(p => p.ciudad).Title("CIUDAD");
                                columns.Bound(p => p.fechaingreso)
                                    .Title("F.Ingreso")
                                    .Format("{0:d}")
                                    //.Format("{0:G}")
                                    .Width(110)
                                ;                                
                            })
                            .ToolBar(tools => tools.Excel())
                            .ToolBar(tools => tools.Pdf())
                            .Excel(excel => excel
                                //.AllPages(true)
                                .FileName("Listado de Clientes.xlsx")
                                .Filterable(true)
                                .ProxyURL(Url.Action("Excel_Export_Save", "Grid"))
                            )
                            .Pdf(pdf => pdf
                                //.AllPages()
                                .AvoidLinks()
                                .PaperSize("letter")
                                .Scale(0.8)
                                .Margin("2cm", "1cm", "1cm", "1cm")
                                .Landscape()
                                .RepeatHeaders()
                                //.TemplateId("page-template")
                                .FileName("Listado de Clientes.pdf")
                                .ProxyURL(Url.Action("Pdf_Export_Save", "Grid"))
                            )  
                            .Pageable()
                            .Sortable()
                            //.Scrollable(scr=>scr.Height(800))
                            //.Scrollable()
                            .Filterable()
                            //.HtmlAttributes(new { style = "height:550px;" })
                            .DataSource(dataSource => dataSource
                                .Ajax()
                                .PageSize(20)
                                .Read(read => read.Action("Cliente_Buscar", "Cliente").Data("dataGridClientes"))
                            )
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>