GestorDeContratos.Web/Controllers/ContratosController.cs
using System;
using System.Net;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GestorDeContratos.BLL.ServiceImplementation;
using GestorDeContratos.ServiceLayer.Service;
using GestorDeContratos.ServiceLayer.ViewsDTOs;
using Kendo.Mvc.Extensions;
using Microsoft.Office.Interop.Word;
using GestorDeContratos.ServiceLayer;
using Aspose.Words;
using Aspose.Words.Tables;
using Aspose.Words.Saving;
using Aspose.Words.Replacing;
using System.Drawing;
using System.Text;
using Kendo.Mvc.UI;
using System.Configuration;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;

namespace GestorDeContratos.Web.Controllers
{
    public class ContratosController : Controller
    {
        readonly IGestorDeContratosSvcImpl gestorDeContratos;

        public ContratosController()
        {
            gestorDeContratos = new GestorDeContratosSvcImpl();
        }

        public ActionResult Details(int id = 0)
        {
            ViewData["RutCliente"] = id;
            PopulateCategories();
            return View();
        }

        public ActionResult Firmados()
        {
            return View();
        }

        public ActionResult PorFirmar()
        {
            return View();
        }

        private void PopulateCategories()
        {
            IEnumerable<EstadoCivilDTO> lista = new List<EstadoCivilDTO>();
            lista = gestorDeContratos.obtenerEstadosCiviles();

            ViewData["categories"] = lista;
            ViewData["defaultCategory"] = lista.First();
        }

        public ActionResult ContratosFEGenerados_Read([DataSourceRequest] DataSourceRequest request, int rutCliente)
        {
            IEnumerable<ContratoFEGeneradoDTO> lista = new List<ContratoFEGeneradoDTO>();
            lista = gestorDeContratos.obtenerContratosFEGenerados(rutCliente);
            return Json(lista.ToDataSourceResult(request));
        }

        public ActionResult ContratosFirmados_Read([DataSourceRequest] DataSourceRequest request)
        {
            IEnumerable<ContratoFirmadoDTO> lista = new List<ContratoFirmadoDTO>();
            lista = gestorDeContratos.obtenerContratosFirmados();
            return Json(lista.ToDataSourceResult(request));
        }

        public ActionResult ContratosPorFirmar_Read([DataSourceRequest] DataSourceRequest request)
        {
            IEnumerable<ContratoPorFirmarDTO> lista = new List<ContratoPorFirmarDTO>();
            lista = gestorDeContratos.obtenerContratosPorFirmar();
            return Json(lista.ToDataSourceResult(request));
        }

        public ActionResult ContratosPorFirmarFirmantes_Read([DataSourceRequest] DataSourceRequest request, int idContratoEnviado)
        {
            IEnumerable<ContratoPorFirmarFirmanteDTO> lista = new List<ContratoPorFirmarFirmanteDTO>();
            lista = gestorDeContratos.obtenerContratosPorFirmar_Firmantes(idContratoEnviado);
            return Json(lista.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ContratosPorFirmar_Destroy([DataSourceRequest] DataSourceRequest request, ContratoPorFirmarDTO contratoPorFirmar)
        {
            var results = new List<RepresentanteClienteDTO>();

            if (contratoPorFirmar != null)
            {
                gestorDeContratos.eliminarContratoPorFirmar(contratoPorFirmar.idContratoEnviado);
            }
            return Json(results.ToDataSourceResult(request, ModelState));
        }

        //Visualizar Contrato Firma Electrónica
        public string Ver(int id = 0)
        {
            string resultado = "";

            IEnumerable<ContratoEnviadoDTO> contratoEnviado = new List<ContratoEnviadoDTO>();
            contratoEnviado = gestorDeContratos.obtenerContratoEnviadoDetalle(id);

            if (contratoEnviado.Count() > 0)
            {
                Response.Clear();
                Response.ContentType = "Application/pdf";
                Response.AppendHeader("Content-Disposition", "inline; filename=" + contratoEnviado.FirstOrDefault().rutCliente + "_" + id + ".pdf");
                Response.BinaryWrite(System.Convert.FromBase64String(contratoEnviado.FirstOrDefault().contratoBase64));
                Response.Flush();
                Response.End();
            }
            else
            {
                resultado = "<p>CONTRATO NO ENCONTRADO!!</p>";
            }

            return resultado;
        }

        //LINEAS
        public string CartaBancoLINEA(string formato, int rutCliente, int? rutR1, int? rutR2)
        {
            string resultado = "";

            try
            {
                IEnumerable<ClienteDTO> cliente = new List<ClienteDTO>();
                cliente = gestorDeContratos.obtenerCliente(rutCliente);

                IEnumerable<RepresentanteClienteDTO> representante1 = new List<RepresentanteClienteDTO>();
                representante1 = gestorDeContratos.obtenerRepresentanteCliente(rutCliente, rutR1);

                IEnumerable<RepresentanteClienteDTO> representante2 = new List<RepresentanteClienteDTO>();
                representante2 = gestorDeContratos.obtenerRepresentanteCliente(rutCliente, rutR2);

                IEnumerable<SucursalDTO> sucursal = new List<SucursalDTO>();
                sucursal = gestorDeContratos.obtenerSucursal(cliente.FirstOrDefault().idSucursal);

                IEnumerable<BancoClienteDTO> bancosCliente = new List<BancoClienteDTO>();
                bancosCliente = gestorDeContratos.obtenerBancoCliente(rutCliente);

                string plantilla = "CartaBanco.docx";

                //string dirPlantillas = Server.MapPath(@"~/Plantillas/").ToString();
                string dirPlantillas = ConfigurationManager.AppSettings["plantillasContratos"];
                string dirDocumentosTemp = Server.MapPath(@"~/Plantillas/TempFiles/").ToString();

                string fileName = (dirPlantillas + plantilla);

                FileStream file = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                Aspose.Words.Document doc = new Aspose.Words.Document(file);
                FindReplaceOptions options = new FindReplaceOptions(FindReplaceDirection.Forward);

                doc.Range.Replace("#Sucursal#", sucursal.FirstOrDefault().nombre, options);
                doc.Range.Replace("#Nombrecliente#", cliente.FirstOrDefault().razonSocial, options);
                doc.Range.Replace("#FechaFirmaContrato#", ((DateTime)cliente.FirstOrDefault().fechaFirmaContrato).ToString("dd' de 'MMMM' de 'yyyy"), options);

                //Datos Representante 1
                if (representante1.Count() > 0)
                {
                    using (var repP = representante1.FirstOrDefault())
                    {
                        doc.Range.Replace("#NombreRepresentanteCliente1#", representante1.FirstOrDefault().nombre, options);
                    }
                }
                else
                {
                    doc.Range.Replace("#NombreRepresentanteCliente1#", "", options);
                }

                //Datos Representante 2
                if (representante2.Count() > 0)
                {
                    using (var repP = representante2.FirstOrDefault())
                    {
                        doc.Range.Replace("#NombreRepresentanteCliente2#", representante2.FirstOrDefault().nombre, options);
                    }
                }
                else
                {
                    doc.Range.Replace("#NombreRepresentanteCliente2#", "", options);
                }


                DocumentBuilder builder = new DocumentBuilder(doc);
                builder.MoveToBookmark("CuentasBanco");
                builder.ParagraphFormat.ClearFormatting();
                builder.StartTable();
                builder.ParagraphFormat.Alignment = ParagraphAlignment.Center;
                builder.CellFormat.VerticalAlignment = CellVerticalAlignment.Center;
                //builder.CellFormat.PreferredWidth = PreferredWidth.FromPercent(70);
                //builder.CellFormat.Width = 100;
                builder.Bold = true;

                builder.InsertCell();
                builder.Write("BANCO");
                builder.InsertCell();
                builder.Write("CUENTA");
                builder.InsertCell();
                builder.Write("TIPO CUENTA");
                builder.EndRow();

                builder.Bold = false;
                foreach (BancoClienteDTO bancoC in bancosCliente)
                {
                    builder.InsertCell();
                    builder.ParagraphFormat.Alignment = ParagraphAlignment.Left;
                    //builder.CellFormat.PreferredWidth = PreferredWidth.FromPercent(8.5);
                    builder.Write(bancoC.banco);
                    builder.InsertCell();
                    builder.ParagraphFormat.Alignment = ParagraphAlignment.Left;
                    //builder.CellFormat.PreferredWidth = PreferredWidth.FromPercent(4);
                    builder.Write(bancoC.cuenta);
                    builder.InsertCell();
                    builder.ParagraphFormat.Alignment = ParagraphAlignment.Left;
                    //builder.CellFormat.PreferredWidth = PreferredWidth.FromPercent(30.5);
                    builder.Write(bancoC.tipoCuenta);
                    builder.EndRow();
                }
                builder.EndTable();


                string fileSaveAs = rutCliente + "_" + System.Reflection.MethodBase.GetCurrentMethod().Name;
                string fileSaveAsPath = "";
                int totalPaginasDocumento = 0;
                if (formato.ToUpper() == "WORD")
                {
                    fileSaveAs = fileSaveAs + ".docx";
                    fileSaveAsPath = dirDocumentosTemp + fileSaveAs;

                    doc.Save(fileSaveAsPath);

                    Response.Clear();

GestorDeContratos.Web/Views/Contratos/Firmados.cshtml
@{
    ViewBag.Title = "Contratos Firmados";
}

<br />

<script>
    kendo.culture("es-CL");
</script>

<div class="container">
    <form id="logForm">
        <div class="panel panel-default">
            <div class="panel-heading"><b>CONTRATOS FIRMADOS</b></div>
            <div class="panel-body">

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-18 col-md-12">
                            @(Html.Kendo().Grid<GestorDeContratos.ServiceLayer.ViewsDTOs.ContratoFirmadoDTO>()
                                .Name("gridContratosFirmados")
                                .Columns(columns =>
                                {
                                    //columns.Command(command =>
                                    //{
                                    //    //command.Destroy();
                                    //})
                                    //.Title("Opciones")
                                    //.Width(120)
                                    //;
                                    columns.Bound(p => p.idContratoEnviado).Width(70);
                                    //columns.Bound(p => p.rutCliente).Width(160);
                                    //columns.Bound(p => p.dvCliente).Width(160);
                                    columns.Bound(p => p.idContratoEnviado).Width(60).ClientTemplate("<a href=\\# onclick=window.open('../Contratos/Ver/#= idContratoEnviado #','contrato','width=800,height=700')>Ver</a>").Title("PDF").Filterable(false);
                                    columns.Bound(p => p.estadoContrato).Width(160).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.TipoOperacion).Width(100).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.nombreContratoTipo).Width(160).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.fechaEnvio)
                                        .Format("{0:g}")
                                        .Width(130)
                                        //.Filterable(ftb => ftb.Multi(true)).Format("{0:d}")
                                    ;
                                    columns.Bound(p => p.usuario).Width(100).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.nombreCliente).Width(160).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.rutCliente)
                                        .Width(120)
                                        //.ClientTemplate("#= rutCliente #-#= dvCliente #")
                                        .ClientTemplate(@Html.ActionLink("#= rutCliente #-#= dvCliente #", "Details", "Contratos", new { id = "#: rutCliente #" }, null).ToString())
                                        .Title("Rut Cliente")
                                        .Filterable(ftb => ftb.Multi(true).Search(true))
                                    ;
                                    columns.Bound(p => p.idSimulaOper).Width(120).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.paginasContrato).Width(100).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.firmado).Width(100).ClientTemplate("<input type='checkbox' ${ firmado == true ? checked='checked' : ''} disabled />").Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.ultimaFirma)
                                        .Format("{0:g}")
                                        .Width(130)
                                    ;
                                    columns.Bound(p => p.fechaOperacion).Format("{0:d}").Width(120);
                                    columns.Bound(p => p.cantidadDocumentos).Width(120);
                                    columns.Bound(p => p.montoDocumentos).Format("{0:c0}").Width(120);
                                    columns.Bound(p => p.montoFinanciado).Format("{0:c0}").Width(120);
                                })
                                
                                .ToolBar(tools => tools.Excel())
                                .ToolBar(tools => tools.Pdf())
                                .Excel(excel => excel
                                    //.AllPages(true)
                                    .FileName("Contratos_Firmados.xlsx")
                                    .Filterable(true)
                                    .ProxyURL(Url.Action("Excel_Export_Save", "Grid"))
                                )
                                .Pdf(pdf => pdf
                                    //.AllPages()
                                    .AvoidLinks()
                                    .PaperSize("letter")
                                    .Scale(0.8)
                                    .Margin("2cm", "1cm", "1cm", "1cm")
                                    .Landscape()
                                    .RepeatHeaders()
                                    //.TemplateId("page-template")
                                    .FileName("Contratos_Firmados.pdf")
                                    .ProxyURL(Url.Action("Pdf_Export_Save", "Grid"))
                                )
                                
                                .Pageable()
                                .Sortable()
                                .Scrollable()
                                .Selectable(selectable => selectable
                                    .Mode(GridSelectionMode.Single)
                                    //.Type(GridSelectionType.Cell)
                                )                                
                                //.PersistSelection()
                                .ClientDetailTemplateId("template")
                                .Filterable()
                                .Resizable(resize => resize.Columns(true))    
                                //.ColumnMenu()
                                .Groupable()
                                .HtmlAttributes(new { style = "height:550px;" })
                                .DataSource(dataSource => dataSource
                                    .Ajax()
                                    .PageSize(2000)
                                    .Model(model =>
                                    {
                                        model.Id(p => p.idContratoEnviado);
                                    })
                                    .Read(read => read.Action("ContratosFirmados_Read", "Contratos"))
                                    //.Destroy(update => update.Action("ContratosPorFirmar_Destroy", "Contratos"))
                                )
                                .Events(events => events.DataBound("dataBound"))
                            )

                            <script id="template" type="text/kendo-tmpl">
                                @(Html.Kendo().Grid<GestorDeContratos.ServiceLayer.ViewsDTOs.ContratoPorFirmarFirmanteDTO>()
                                    .Name("grid_#=idContratoEnviado#") // template expression, to be evaluated in the master context
                                    .Columns(columns =>
                                    {
                                        //columns.Bound(o => o.rutFirmante).Width(100);
                                        //columns.Bound(o => o.dvFirmante).Width(100);
                                        columns.Bound(p => p.rutFirmante).Width(120).ClientTemplate("\\#= rutFirmante \\#-\\#= dvFirmante \\#").Title("Rut Firmante");
                                        columns.Bound(o => o.nombreFirmante).Width(350);
                                        //columns.Bound(o => o.fechaIngreso).Format("{0:d}").Width(130);
                                        columns.Bound(o => o.firmado).Width(100).ClientTemplate("<input type='checkbox' \\#= firmado ? 'checked=checked' : '' \\# disabled='disabled' >");
                                        columns.Bound(o => o.fechaFirmado)
                                            //.Format("{0:d}")
                                            .Format("{0:g}")
                                            .Width(150);
                                        columns.Bound(o => o.Descripcion).Width(150);
                                        columns.Bound(o => o.idVersionAcuerdoLegal);
                                    })
                                    .Selectable(selectable => selectable
                                        .Mode(GridSelectionMode.Single)
                                    )                                
                                    .DataSource(dataSource => dataSource
                                        .Ajax()
                                        .PageSize(10)
                                        .Read(read => read.Action("ContratosPorFirmarFirmantes_Read", "Contratos", new { idContratoEnviado = "#=idContratoEnviado#" }))
                                    )
                                    .Pageable()
                                    .Sortable()
                                    .ToClientTemplate()
                                )
                            </script>
                            <script>
                                function dataBound() {
                                    //this.expandRow(this.tbody.find("tr.k-master-row").first());
                                }
                            </script>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>

GestorDeContratos.Web/Views/Contratos/PorFirmar.cshtml
@{
    ViewBag.Title = "Contratos Por Firmar";
}

<br />

<script>
    kendo.culture("es-CL");
</script>

<div class="container">
    <form id="logForm">
        <div class="panel panel-default">
            <div class="panel-heading"><b>CONTRATOS POR FIRMAR</b></div>
            <div class="panel-body">

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-18 col-md-12">
                            @(Html.Kendo().Grid<GestorDeContratos.ServiceLayer.ViewsDTOs.ContratoPorFirmarDTO>()
                                .Name("gridContratosPorFirmar")
                                .Columns(columns =>
                                {
                                    columns.Command(command =>
                                    {
                                        command.Destroy();
                                    })
                                    .Title("Opciones")
                                    .Width(110)
                                    ;
                                    columns.Bound(p => p.idContratoEnviado).Width(70);
                                    //columns.Bound(p => p.rutCliente).Width(160);
                                    //columns.Bound(p => p.dvCliente).Width(160);
                                    columns.Bound(p => p.idContratoEnviado).Width(60).ClientTemplate("<a href=\\# onclick=window.open('../Contratos/Ver/#= idContratoEnviado #','contrato','width=800,height=700')>Ver</a>").Title("PDF").Filterable(false);
                                    columns.Bound(p => p.estadoContrato).Width(140).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.TipoOperacion).Width(100).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.nombreContratoTipo).Width(160).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.fechaEnvio)
                                        .Format("{0:g}")
                                        .Width(130)
                                    ;
                                    columns.Bound(p => p.usuario).Width(90).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.nombreCliente).Width(160).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.rutCliente)
                                        .Width(110)
                                        //.ClientTemplate("#= rutCliente #-#= dvCliente #")
                                        .ClientTemplate(@Html.ActionLink("#= rutCliente #-#= dvCliente #", "Details", "Contratos", new { id = "#: rutCliente #" }, null).ToString())
                                        .Title("Rut Cliente")
                                    ;
                                    columns.Bound(p => p.idSimulaOper).Width(120).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.paginasContrato).Width(100).Filterable(ftb => ftb.Multi(true).Search(true));
                                    columns.Bound(p => p.firmado).Width(100).ClientTemplate("<input type='checkbox' ${ firmado == true ? checked='checked' : ''} disabled />")
                                        .Filterable(ftb => ftb.Multi(true).Search(true))
                                    ;
                                    columns.Bound(p => p.fechaOperacion).Format("{0:d}").Width(120);
                                    columns.Bound(p => p.cantidadDocumentos).Width(120);
                                    columns.Bound(p => p.montoDocumentos).Format("{0:c0}").Width(120);
                                    columns.Bound(p => p.montoFinanciado).Format("{0:c0}").Width(120);
                                })
                                
                                .ToolBar(tools => tools.Excel())
                                .ToolBar(tools => tools.Pdf())
                                .Excel(excel => excel
                                    //.AllPages(true)
                                    .FileName("Contratos_Por_Firmar.xlsx")
                                    .Filterable(true)
                                    .ProxyURL(Url.Action("Excel_Export_Save", "Grid"))
                                )
                                .Pdf(pdf => pdf
                                    //.AllPages()
                                    .AvoidLinks()
                                    .PaperSize("letter")
                                    .Scale(0.8)
                                    .Margin("2cm", "1cm", "1cm", "1cm")
                                    .Landscape()
                                    .RepeatHeaders()
                                    //.TemplateId("page-template")
                                    .FileName("Contratos_Por_Firmar.pdf")
                                    .ProxyURL(Url.Action("Pdf_Export_Save", "Grid"))
                                )

                                .Pageable()
                                .Sortable()
                                .Scrollable()
                                .Selectable(selectable => selectable
                                    .Mode(GridSelectionMode.Single)
                                    //.Type(GridSelectionType.Cell)
                                )                                
                                //.PersistSelection()
                                .ClientDetailTemplateId("template")
                                .Filterable()
                                .Resizable(resize => resize.Columns(true))    
                                //.ColumnMenu()
                                .Groupable()
                                .HtmlAttributes(new { style = "height:550px;" })
                                .DataSource(dataSource => dataSource
                                    .Ajax()
                                    .PageSize(1000)
                                    .Model(model =>
                                    {
                                        model.Id(p => p.idContratoEnviado);
                                    })
                                    .Read(read => read.Action("ContratosPorFirmar_Read", "Contratos"))
                                    .Destroy(update => update.Action("ContratosPorFirmar_Destroy", "Contratos"))
                                )
                                .Events(events => events.DataBound("dataBound"))
                            )

                            <script id="template" type="text/kendo-tmpl">
                                @(Html.Kendo().Grid<GestorDeContratos.ServiceLayer.ViewsDTOs.ContratoPorFirmarFirmanteDTO>()
                                    .Name("grid_#=idContratoEnviado#") // template expression, to be evaluated in the master context
                                    .Columns(columns =>
                                    {
                                        //columns.Bound(o => o.rutFirmante).Width(100);
                                        //columns.Bound(o => o.dvFirmante).Width(100);
                                        columns.Bound(p => p.rutFirmante).Width(120).ClientTemplate("\\#= rutFirmante \\#-\\#= dvFirmante \\#").Title("Rut Firmante");
                                        columns.Bound(o => o.nombreFirmante).Width(350);
                                        //columns.Bound(o => o.fechaIngreso).Format("{0:d}").Width(130);
                                        columns.Bound(o => o.firmado).Width(100).ClientTemplate("<input type='checkbox' \\#= firmado ? 'checked=checked' : '' \\# disabled='disabled' >");
                                        columns.Bound(o => o.fechaFirmado)
                                            //.Format("{0:d}")
                                            .Format("{0:g}")
                                            .Width(150);
                                        columns.Bound(o => o.Descripcion).Width(150);
                                        columns.Bound(o => o.idVersionAcuerdoLegal);
                                    })
                                    .Selectable(selectable => selectable
                                        .Mode(GridSelectionMode.Single)
                                    )                                
                                    .DataSource(dataSource => dataSource
                                        .Ajax()
                                        .PageSize(10)
                                        .Read(read => read.Action("ContratosPorFirmarFirmantes_Read", "Contratos", new { idContratoEnviado = "#=idContratoEnviado#" }))
                                    )
                                    .Pageable()
                                    .Sortable()
                                    .ToClientTemplate()
                                )
                            </script>
                            <script>
                                function dataBound() {
                                    //this.expandRow(this.tbody.find("tr.k-master-row").first());
                                }
                            </script>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>